### ISSUE TITLE
All it still needs is a Purge-all option

### ISSUE THREAD

**Issue by dandrejvv** [ButchersBoy/QSet#1]
Hi

This is a great piece of MSMQ Administration software, the only thing that it still needs is a "Purge All Queues" option. I haven't found it in the current application and if you don't have the capacity, I'm happy to fork this project, add it in and to send you a pull request if you are happy to do so.

**Comment by ButchersBoy** [comment]
I'm  not actively maintaining this, but will accept PRs.

**Comment by dandrejvv** [comment]
Ok, great. I've just finished coding it. Just need to test it a bit and make sure it all works. I've pushed it to my fork so long.

**Comment by ButchersBoy** [comment]
Cool. Just let me know when ready. I'll probably try and compile a exe/release at that point using the 3rd party libs. I tried to get to get some form of open licence for it, but the said 3rd party declined.  :(

**Comment by dandrejvv** [comment]
Would you be able to build it without the whole "license required" stuff, when you open the app? (Or is there an easier way to get around it?)
Also, I've noticed that the Debug build shows "evaluation" on all the controls.

**Comment by dandrejvv** [comment]
You're welcome. I hope, presume the work was sufficient ;-)
The only stuff that now is a hindrence is the evaluation on those third party controls and the application licensing that can potentially now be dropped since this is now an open source version.
